require File.dirname(__FILE__) + "/dreamcatch/config"
require File.dirname(__FILE__) + "/dreamcatch/dav"
require File.dirname(__FILE__) + "/dreamcatch/dav_response"
require File.dirname(__FILE__) + "/dreamcatch/web_dav"
require File.dirname(__FILE__) + "/dreamcatch/repo"

require "rubygems"
require "grit"
require "open3"
require "base64"